<?php

namespace AppBundle\Repository;

/**
 * AdditionalItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
