<?php

namespace AppBundle\Repository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{
    public function surfaceAreas($job)
    {
        return $this->createQueryBuilder('j')
            ->select('sn.name, SUM(s.surfaceTotalArea)')
            ->leftjoin('j.area','a')
            ->leftJoin('a.surface', 's')
            ->leftJoin('s.surfaceName','sn')
            ->groupBy('sn.name')
            ->where('a.job = :job')
            ->setParameter('job',$job)
            ->getQuery()
            ->getResult();
    }



}
