<?php

namespace AppBundle\Repository;

/**
 * OrderItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
