<?php

namespace AppBundle\Repository;

/**
 * SurfaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurfaceRepository extends \Doctrine\ORM\EntityRepository
{

}
