<?php

namespace AppBundle\Repository;

/**
 * SurfaceNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurfaceNameRepository extends \Doctrine\ORM\EntityRepository
{
}
