imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
#    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        pathToWeb: "%kernel.root_dir%/../web"
        webToWeb: "http://localhost/orders/web"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#    encryption: ssl
#    auth_mode:  login
    spool:     { type: memory }

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        [AppBundle]
    #java: /usr/bin/java

    filters:
        #less:
            #node: "C:\\Program Files\\nodejs\\node.exe"
            #node_paths: [C:\\Users\\James\\AppData\\Roaming\\npm\\node_modules]
            #apply_to: ".less$"

            #bin: /usr/bin/less
            #apply_to: '.less$'

        cssrewrite: ~

avanzu_admin_theme:
    use_twig   : true
    enable_demo: false
    theme:
        default_avatar   : bundles/avanzuadmintheme/img/avatar.png
#        skin             : skin-black  # see skin listing for viable options
        skin             : skin-red  # see skin listing for viable options
        fixed_layout     : false      # -------------------------------------------------------
        boxed_layout     : false      # these settings relate directly to the "Layout Options"
        collapsed_sidebar: true      # described in the adminlte documentation
        mini_sidebar     : true      # -------------------------------------------------------
        control_sidebar  : false      # controls wether the right hand panel will be rendered

    knp_menu:                         # knp menu integration
        enable         : true
        main_menu      : avanzu_main  # the menu builder alias to use for the main menu
        breadcrumb_menu: false        # the menu builder alias to use for the breacrumbs

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address:        info@encapsulatedservices.com
        sender_name:    noreply
#    group:
#        group_class: hounded\hsBundle\Entity\Group
#    registration:
#        form:
#            type: hounded\hsBundle\Form\RegistrationType

knp_snappy:
    pdf:
        enabled:    true
        binary:     "\"C:\\Program Files (x86)\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
#        binary:     /usr/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     "\"C:\\Program Files (x86)\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
#        binary:     /usr/bin/wkhtmltoimage
        options:    []


#Braincrafted Configuration
braincrafted_bootstrap:
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js
    css_preprocessor: less # "less", "lessphp", "sass" or "none"
    fonts_dir: %kernel.root_dir%/../web/fonts
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig
