# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
            AppBundle\Entity\User:
                algorithm: bcrypt
            FOS\UserBundle\Model\UserInterface: bycrpt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: fos_user_profile_show
                require_previous_session: false
            logout:     true
            anonymous:  true
            remember_me:
                secret:   '%secret%'
                lifetime: 15552000 # 1 week in seconds
                path:     /
                domain:   ~

    role_hierarchy:
        ROLE_ADMIN:   ROLE_ADMIN


    access_control:
         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin, role: ROLE_ADMIN }
